# This file was generated by GoReleaser. DO NOT EDIT.
cask "claws" do
  version "0.18.0"

  on_macos do
    on_intel do
      sha256 "073bd7c51dcef1301a3c31ba0981c8ff5c2c77210004025c227de69af7981912"
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "e404a19d43d4c86b74befcc4fbc8c4fc273392c55f00760b437213ac34f82b81"
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a93869757952301c7b3f545bd851d596e7b3e91b1296bd9acac8cfc3551b9200"
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "5ade6d0023651543932cea3269753cca2190fd8e4a6f5f7a3ec0ba78405b871e"
      url "https://github.com/clawscli/claws/releases/download/v#{version}/claws-linux-arm64.tar.gz"
    end
  end

  name "claws"
  desc "Terminal UI for AWS resource management"
  homepage "https://github.com/clawscli/claws"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claws"

  postflight_steps do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claws"]
    end
  end

  # No zap stanza required

end
